# Copyright 2025 Sudo Sweden AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: golang-generate
inputs:
  generate-path:
    description: Path to run go generate on
    required: false
    default: './...'
description: Runs `go generate` and checks for uncommitted changes
runs:
  using: "composite"
  steps:
    - shell: bash
      run: go generate ${{ inputs.generate-path }}
    - shell: bash
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::error::Generated files are not up to date. Please run 'go generate ${{ inputs.generate-path }}' and commit the results."
          git status
          git diff
          exit 1
        fi

