name: golang-lint
inputs:
  golangci-version:
    required: false
    default: v2.1.6
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5.5.0
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: ${{ inputs.golangci-version }}
