name: AI Code Review
description: Run the SUDO AI reviewer on pull request diffs.
author: Sudo Sweden AB

inputs:
  openai_api_key:
    description: OpenAI API key used for the review request
    required: true
  github_token:
    description: GitHub token used for posting review comments
    required: true

runs:
  using: composite
  steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Run AI review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ github.action_path }}
      run: go run .
